export const currencies: { [code: string]: { name: string, flag: string } } = {
  USD: { name: 'United States Dollar', flag: 'us' },
  EUR: { name: 'Euro', flag: 'eu' },
  JPY: { name: 'Japanese Yen', flag: 'jp' },
  GBP: { name: 'British Pound', flag: 'gb' },
  AUD: { name: 'Australian Dollar', flag: 'au' },
  CAD: { name: 'Canadian Dollar', flag: 'ca' },
  CHF: { name: 'Swiss Franc', flag: 'ch' },
  CNY: { name: 'Chinese Yuan', flag: 'cn' },
  INR: { name: 'Indian Rupee', flag: 'in' },
  BRL: { name: 'Brazilian Real', flag: 'br' },
  RUB: { name: 'Russian Ruble', flag: 'ru' },
  ZAR: { name: 'South African Rand', flag: 'za' },
  NGN: { name: 'Nigerian Naira', flag: 'ng' },
  KES: { name: 'Kenyan Shilling', flag: 'ke' },
  GHS: { name: 'Ghanaian Cedi', flag: 'gh' },
  EGP: { name: 'Egyptian Pound', flag: 'eg' },
  PKR: { name: 'Pakistani Rupee', flag: 'pk' },
  BDT: { name: 'Bangladeshi Taka', flag: 'bd' },
  VND: { name: 'Vietnamese Dong', flag: 'vn' },
  PHP: { name: 'Philippine Peso', flag: 'ph' },
  MYR: { name: 'Malaysian Ringgit', flag: 'my' },
  THB: { name: 'Thai Baht', flag: 'th' },
  IDR: { name: 'Indonesian Rupiah', flag: 'id' },
  SGD: { name: 'Singapore Dollar', flag: 'sg' },
  KRW: { name: 'South Korean Won', flag: 'kr' },
  MXN: { name: 'Mexican Peso', flag: 'mx' },
  ARS: { name: 'Argentine Peso', flag: 'ar' },
  CLP: { name: 'Chilean Peso', flag: 'cl' },
  COP: { name: 'Colombian Peso', flag: 'co' },
  TRY: { name: 'Turkish Lira', flag: 'tr' },
  ILS: { name: 'Israeli Shekel', flag: 'il' },
  AED: { name: 'UAE Dirham', flag: 'ae' },
  SAR: { name: 'Saudi Riyal', flag: 'sa' },
  USDC: { name: 'USD Coin', flag: 'us' },
};
